# Generated by Django 4.1 on 2023-01-10 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialapp", "0002_profile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="liked_by",
        ),
        migrations.AddField(
            model_name="posts",
            name="num_likes",
            field=models.ManyToManyField(
                related_name="num_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                max_length=200,
                null=True,
            ),
        ),
    ]
