# Generated by Django 4.1 on 2023-01-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialapp", "0003_remove_posts_liked_by_posts_num_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="myuser",
            name="bio",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
